version: "3.8"
services:
  pg-docker:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: music
    ports:
      - 6432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
